package pl.ksikora.filmreviewerbackend.advice;

public enum Error {
    USER_ALREADY_EXISTS,
    USERNAME_NOT_FOUND,
    BAD_CREDENTIALS,
    NULL_NICKNAME_ERROR,
    BLANK_NICKNAME_ERROR,
    NULL_EMAIL_ERROR,
    BLANK_EMAIL_ERROR,
    NULL_PASSWORD_ERROR,
    BLANK_PASSWORD_ERROR,
    TOKEN_EXPIRED,
    TOKEN_REVOKED,
    TOKEN_NOT_FOUND,
    TOKEN_INVALID
}